lzc-sdk-version: "0.1"
name: coco-ai
package: xu.deploy.coco-ai
version: 0.8.0
description: coco-ai
homepage: https://coco.rs/#install
author: xu
application:
  subdomain: coco-ai
  public_path:
    - /
  background_task: false
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://coco.xu.deploy.coco-ai.lzcapp:9000/
services:
  coco:
    image: registry.lazycat.cloud/u04123229/infinilabs/coco:50a708da58d804c8
    environment:
      - EASYSEARCH_INITIAL_ADMIN_PASSWORD=coco-server
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    binds:
      - /lzcapp/var/data:/app/easysearch/data
